#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_RX_CHANNEL_COUNT 16
#define APP_MAX_SELECTED_ITEM_LEN 32
#define APP_MAX_DIALOG_STATE_LEN 32
#define APP_MAX_ERROR_TEXT_LEN 96
#define APP_MAX_SSID_LEN 32
#define APP_MAX_IP_LEN 16
#define APP_MAX_HOSTNAME_LEN 32
#define APP_MAX_PROFILE_NAME_LEN 32
#define APP_MAX_PROFILE_PATH_LEN 128
#define APP_MAX_DIAGNOSTIC_MESSAGE_LEN 96
#define APP_MAX_FLIGHT_MODE_LEN 16
#define APP_MAX_PROFILE_LIST_ITEMS 24

#define APP_WIFI_SOFTAP_SSID "CRSF-Display"
#define APP_WIFI_SOFTAP_PASSWORD ""
#define APP_WIFI_SOFTAP_MAX_CONNECTIONS 4

#define APP_SIMULATOR_DEFAULT_PROFILE_DIR "/sdcard/crsf-display/profiles/"
#define APP_SIMULATOR_DEFAULT_PROFILE_PATH "/sdcard/crsf-display/profiles/default.json"
#define APP_SIMULATOR_DEFAULT_PROFILE_NAME "default.json"

#define APP_CRSF_UART_PORT_NAME "UART2"
#define APP_GPS_PROTOCOL_NAME "NMEA 0183"
#define APP_GPS_SERIAL_TYPE_NAME "software_uart"

#define APP_GPS_RX_GPIO 21
#define APP_GPS_TX_GPIO 22
#define APP_GPS_BAUD_RATE 9600

#define APP_SDCARD_MOSI_GPIO 23
#define APP_SDCARD_MISO_GPIO 19
#define APP_SDCARD_SCLK_GPIO 18
#define APP_SDCARD_CS_GPIO 4

#define APP_HTTP_SERVER_PORT 80
#define APP_HTTP_MAX_URI_HANDLERS 24
#define APP_HTTP_SERVER_STACK_SIZE 8192

#define APP_EVENTS_QUEUE_LENGTH 24

#define APP_NVS_NAMESPACE "crsf_display"
#define APP_NVS_KEY_GPS_SOURCE "gps_source"
#define APP_NVS_KEY_MANUAL_TLM "manual_tlm"
#define APP_NVS_KEY_PROFILE_PATH "profile_path"

#define APP_TASK_STACK_MEDIUM 4096
#define APP_TASK_STACK_LARGE 6144
#define APP_TASK_STACK_BOOTSTRAP 8192
#define APP_TASK_PRIORITY_NORMAL 5
#define APP_TASK_PRIORITY_IO 6

#define APP_UI_REFRESH_MS 250
#define APP_CRSF_STUB_REFRESH_MS 100
#define APP_TELEMETRY_TX_REFRESH_MS 200
#define APP_SIMULATOR_REFRESH_MS 200
#define APP_GPS_STUB_REFRESH_MS 500
#define APP_WEB_SSE_INTERVAL_MS 1000
#define APP_WEB_SSE_MAX_BURST_COUNT 60

#endif
